### PR TITLE
Update emoji's to emoji 14

### PR DESCRIPTION
**Pull request by Hystersis**
#203 
This pull request is to update vue-emoji-mart to the latest Emoji v14 specification.

- Updated data source URLs in `css/emoji-mart.css` to match Emoji v14
- Data was rebuilt in `data/` files with `npm run build:data`
- Rebuilt `dist/` files
- In `docs.app.vue`:
    - **47** Add `:key` to address Vue issue [that v-for now needs a key to function](https://vuejs.org/guide/essentials/list.html#v-for-with-a-component:~:text=You%20can%20directly%20use%20v%2Dfor%20on%20a%20component%2C%20like%20any%20normal%20element%20(don%27t%20forget%20to%20provide%20a%20key)%3A)
    - **284** Update style to the latest emoji specification
- `Package-lock.json` updated with npm
- `package.json` updated to the latest `emoji-datasource`
- In `scripts/build.js`, `emoji-datasource` updated their specifications to make all skin tones part of the category `component` instead of `Skin Tones` meaning that `subcategory` has to be used
- In `src/utils/emoji-data.js`:
    - **4** npm change
    - **6** Updated `SHEET_COLUMNS` to [latest numbers](https://github.com/missive/emoji-mart/blob/5d04680c0503410752256ed1f744166ac48ee219/packages/emoji-mart-data/build.js#L43)
    - **499-501** Changed `get_position` to better reflect [Missive's approach to x and y](https://github.com/missive/emoji-mart/blob/f996d91edea9f244103caafe1563ec81155478fb/packages/emoji-mart/src/components/Emoji/Emoji.js#L71-L72)
    - **561** updated line to reflect [Missive](https://github.com/missive/emoji-mart/blob/f996d91edea9f244103caafe1563ec81155478fb/packages/emoji-mart/src/components/Emoji/Emoji.js#L67-L69) which eliminated visual artifacts from other emojis in the `picker`

### CODE REVIEW

**Comment by serebrov** [comment]
@Hystersis Thanks for the pull request. Is it ready for the review or are you going to do some more work here?

I see that tests [are failing on CI](https://app.circleci.com/pipelines/github/serebrov/emoji-mart-vue/209/workflows/21a60394-ccb6-4c76-b255-0289a044ffd5/jobs/195). Can you go through and fix them? (if not: let me know, I'll do it myself later, looks like there are mostly non-functional failures).

Also: are there any limitations related to the update?
Previous emoji version upgrades had some breaking changes, do we have some breaking changes with this update?

**Comment by Hystersis** [comment]
@serebrov it is ready for review, that [previous commit](https://github.com/serebrov/emoji-mart-vue/pull/205/commits/ef1d1b265db77006c8fca5eeb677aa544307a4e1) was just to fix up the prettier issues. I am happy to fix the tests. Yet to have found any breaking changes.

**Comment by serebrov** [comment]
Thanks! There are still some tests failing, I will merge this to a branch first, do more updates to tests and test it manually and release if everything is OK.

**Comment by serebrov** [comment]
Published emoji-mart-vue-fast v11.0.0 to npm.

**Pull request merged**
