### PR TITLE
Add support for emojis 13.0

### PR DESCRIPTION
**Pull request by sgtaziz**
Changes:
* Update to emoji-datasource 6.0.1
* Update to emojilib 3.0.1
  * This required changes in the build script, as `emojilib.lib` no longer exists. See build.js diff.
* Update CSS stylesheet to use emoji-datasource 6.0.1 spritesheet
* Modified `SHEET_COLUMNS` respectively, as there is now 57 instead of 56.

### CODE REVIEW

**Comment by serebrov** [comment]
@sgtaziz thanks! it looks good, I'll pull this on a branch, adjust tests and docs and release after that.

**Comment by serebrov** [comment]
I found one issue here - some apple/google/facebook/twitter emojis are misplaced, here is how native emojis look:

Screenshot 2021-03-20 at 19 15 10

And this is apple (other non-native emojis are similar):

Screenshot 2021-03-20 at 19 15 21



@sgtaziz I'll try to debug this, but if you have some ideas, please share.

**Comment by sgtaziz** [comment]
I noticed a similar issue when I was using the /dist build. Though from source, it seems okay for me. Here is some screenshots:
Apple:
Screen Shot 2021-03-20 at 20 23 54
Native:
Screen Shot 2021-03-20 at 20 24 20

From what I can tell, it seems like the style_x and style_y for your emojis are not updated. Maybe some how the .json data files are not updated or cached?

**Comment by serebrov** [comment]
@sgtaziz hm, strange, it looks like it works if I use the versions of data files from this PR, but if I run `npm run build` (which also runs the build script) then it creates new data files that have the issue.

**Comment by sgtaziz** [comment]
@serebrov might be a dumb question, but did you run yarn/npm to update the packages? I personally use yarn, so I know the yarn.lock file is okay at least

**Comment by serebrov** [comment]
@sgtaziz ah! silly, I needed to run `npm install` to update the dependencies.

**Comment by sgtaziz** [comment]
@serebrov happens to the best of us 😅 Glad you got it working!

**Pull request merged**
