### PR TITLE
Susnux: feat emoji 15

### PR DESCRIPTION
**Pull request by serebrov**
A branch to test, merge, and release the original change from #270.

### CODE REVIEW

**Comment by serebrov** [comment]
Testing it locally, everything looks good except google emojis: they seem to be shifted.

For example, native smiles:

Screenshot 2023-06-10 at 23 13 27

And google:

Screenshot 2023-06-10 at 23 13 50

**Comment by susnux** [comment]
> Testing it locally, everything looks good except google emojis: they seem to be shifted.

This is known, I have submitted a patch. We need to update to version 15.0.1 :)

**Comment by serebrov** [comment]
Related: https://github.com/iamcal/emoji-data/pull/228/files and https://github.com/iamcal/emoji-data/pull/226.

We actually already have v 15.0.1 in the package.json, but links in the CSS files pointed to 15.0.0, fixed in [7be8109](https://github.com/serebrov/emoji-mart-vue/pull/273/commits/7be8109837136ad162c7004b0dc0d267ce1f45e9)

**Comment by serebrov** [comment]
@susnux I published version 15.0.0 with emoji 15 update, thanks for your help!

**Pull request merged**
